# Generated by Django 4.1.1 on 2023-09-02 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.FloatField(default=0)),
                ('like_dislike', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignment',
                'db_table': 'assignment',
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=500)),
                ('longitude', models.CharField(max_length=500)),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'CheckIn',
                'verbose_name_plural': 'CheckIns',
                'db_table': 'check_in',
            },
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Criteria',
                'verbose_name_plural': 'Criterias',
                'db_table': 'criteria',
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Day',
                'verbose_name_plural': 'Days',
                'db_table': 'day',
            },
        ),
        migrations.CreateModel(
            name='GameElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('goal', models.IntegerField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('public', models.BooleanField(default=1)),
            ],
            options={
                'verbose_name': 'GameElement',
                'verbose_name_plural': 'GameElements',
                'db_table': 'game_element',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(default='rayuelaApp/static/project_image/rio.jpg', upload_to='rayuelaApp/static/project_image/')),
                ('available', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='ProjectArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'ProjectArea',
                'verbose_name_plural': 'ProjectAreas',
                'db_table': 'project_area',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('gameelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rayuelaApp.gameelement')),
            ],
            options={
                'verbose_name': 'Challenge',
                'verbose_name_plural': 'Challenges',
                'db_table': 'challenge',
            },
            bases=('rayuelaApp.gameelement',),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(default='rayuelaApp/static/profile_image/user.png', upload_to='rayuelaApp/static/profile_image/')),
                ('verified', models.BooleanField(default=False)),
                ('projects', models.ManyToManyField(to='rayuelaApp.project')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rayuelaApp.role')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=30)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rayuelaApp.user')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'db_table': 'token',
            },
        ),
        migrations.CreateModel(
            name='TimeRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_from', models.DateField(blank=True, max_length=10, null=True)),
                ('date_to', models.DateField(blank=True, max_length=10, null=True)),
                ('hour_from', models.CharField(blank=True, max_length=10, null=True)),
                ('hour_to', models.CharField(blank=True, max_length=10, null=True)),
                ('days', models.ManyToManyField(to='rayuelaApp.day')),
            ],
            options={
                'verbose_name': 'TimeRestriction',
                'verbose_name_plural': 'TimesRestrictions',
                'db_table': 'time_restriction',
            },
        ),
        migrations.CreateModel(
            name='Scoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.IntegerField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rayuelaApp.assignment')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rayuelaApp.criteria')),
            ],
            options={
                'verbose_name': 'Scoring',
                'verbose_name_plural': 'Scorings',
                'db_table': 'scoring',
            },
        ),
        migrations.CreateModel(
            name='ProjectSubArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_area', models.TextField(max_length=800)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rayuelaApp.projectarea')),
            ],
            options={
                'verbose_name': 'ProjectSubArea',
                'verbose_name_plural': 'ProjectSubAreas',
                'db_table': 'project_subarea',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='admins',
            field=models.ManyToManyField(related_name='admins', to='rayuelaApp.user'),
        ),
        migrations.AddField(
            model_name='project',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rayuelaApp.projectarea'),
        ),
        migrations.AddField(
            model_name='project',
            name='time_restriction',
            field=models.ManyToManyField(to='rayuelaApp.timerestriction'),
        ),
        migrations.AddField(
            model_name='gameelement',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rayuelaApp.projectsubarea'),
        ),
        migrations.AddField(
            model_name='gameelement',
            name='checkin',
            field=models.ManyToManyField(related_name='%(class)s_checkins', to='rayuelaApp.checkin'),
        ),
        migrations.AddField(
            model_name='gameelement',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rayuelaApp.user'),
        ),
        migrations.AddField(
            model_name='gameelement',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s', to='rayuelaApp.project'),
        ),
        migrations.AddField(
            model_name='gameelement',
            name='time_restriction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rayuelaApp.timerestriction'),
        ),
        migrations.AddField(
            model_name='gameelement',
            name='user_actives',
            field=models.ManyToManyField(related_name='%(class)s_actives', to='rayuelaApp.user'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rayuelaApp.project'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rayuelaApp.user'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='game_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rayuelaApp.gameelement'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rayuelaApp.user'),
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('gameelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rayuelaApp.gameelement')),
                ('image', models.ImageField(default='rayuelaApp/static/game_elements_image/ge.jpg', upload_to='rayuelaApp/static/game_elements_image/')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rayuelaApp.badge')),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'db_table': 'badge',
            },
            bases=('rayuelaApp.gameelement',),
        ),
    ]
