# Generated by Django 4.1.1 on 2023-10-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rayuelaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='web',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
