services:
 rayuela-be:
   build: .
   container_name: rayuela-be
   ports:
     - "8000:8000"
#   volumes:
#     - .:/app
 #  depends_on:
 #   - db
 #  environment:
 #    DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
 #    DEBUG: ${DEBUG}
#     DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
#     DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
#   env_file:
#     - .env
#volumes:
#  rayuela-be:
