"""
Django settings for rayuela project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
from decouple import config
from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATICFILES_DIRS=(  os.path.join(BASE_DIR,'static'),)
  
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-h=3s!lyn+ko3lq3(a)t&hc_&&*19yj0il)l6w8d8d$6u+tyklt"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django.contrib.contenttypes',
    # third apps
    'rest_framework',
    'corsheaders',
    # local apps
    'rayuelaApp',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "rayuela.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                'django_settings_export.settings_export',
            ],
        },
    },
]

WSGI_APPLICATION = "rayuela.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": config('MYSQL_DB'),
        'USER' : config('MYSQL_USER'),
        'PASSWORD': config('MYSQL_PASSWORD'),
        'HOST': config('MYSQL_HOST'),
        'PORT':config('MYSQL_PORT')
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "es-eu"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"
MEDIA_URL = ''
MEDIA_ROOT = ''

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:5173",
    "http://localhost:5173",
]

EMAIL_BACKEND=config('EMAIL_BACKEND')
EMAIL_HOST=config('EMAIL_HOST')
EMAIL_USE_TLS=config('EMAIL_USE_TLS')
EMAIL_PORT=config('EMAIL_PORT')
EMAIL_HOST_USER=config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD=config('EMAIL_HOST_PASSWORD')

#from django.core.mail import send_mail
#send_mail('Asunto', 'Mensaje', 'gameuxlegacy@gmail.com', ['micaberoy18@gmail.com'], fail_silently=False )

NAVBAR_COLOR=config('NAVBAR_COLOR')

#ROOT NAVBAR
ROOT_CREATE_ADMIN=config('ROOT_CREATE_ADMIN')
ROOT_CREATE_PROJECT=config('ROOT_CREATE_PROJECT')
ROOT_VIEW_PROJECTS=config('ROOT_VIEW_PROJECTS')
#

#ADMIN NAVBAR
ADMIN_CREATE_BADGE=config('ADMIN_CREATE_BADGE')
ADMIN_CREATE_CHALLENGE=config('ADMIN_CREATE_CHALLENGE')
#

#PLAYER NAVBAR
PLAYER_SEE_MY_GE=config('PLAYER_SEE_MY_GE')
PLAYER_CREATE_CHECKIN=config('PLAYER_CREATE_CHECKIN')
PLAYER_SEE_ALL_PROJECTS=config('PLAYER_SEE_ALL_PROJECTS')
PLAYER_MY_PROJECTS=config('PLAYER_MY_PROJECTS')
#

#ROOT_HEADER
ROOT_HEADER=config('ROOT_HEADER')

#PROJECT_TITLE
PROJECT_TITLE=config('PROJECT_TITLE')
#

#TIME_RESTRICTION
CREATE_TIME_RESTRICTION=config('CREATE_TIME_RESTRICTION')
#

#BUTTON
REGISTER_BUTTON=config('REGISTER_BUTTON')
MODIFY_BUTTON=config('MODIFY_BUTTON')
DISJOIN_BUTTON=config('DISJOIN_BUTTON')
#

SETTINGS_EXPORT = [
    'ROOT_CREATE_ADMIN',
    'ROOT_CREATE_PROJECT',
    'ROOT_HEADER',
    'PROJECT_TITLE',
    'ADMIN_CREATE_BADGE',
    'ADMIN_CREATE_CHALLENGE',
    'PLAYER_CREATE_CHECKIN',
    'PLAYER_SEE_MY_GE',
    'PLAYER_SEE_ALL_PROJECTS',
    'PLAYER_MY_PROJECTS',
    'CREATE_TIME_RESTRICTION',
    'REGISTER_BUTTON',
    'ROOT_VIEW_PROJECTS',
    'MODIFY_BUTTON',
    'DISJOIN_BUTTON'
]